- .gitignore
- README.md
- bin/www
- controllers/sessions.js
- package.json
- spec/models/post.spec.js
- spec/mongodb_helper.js
> Fix a few webstorm inspection warnings, make the readme better

- app.js
- bin/www
- package.json
- public/stylesheets/style.css
- spec/mongodb_helper.js
- views/layout.hbs
- views/sessions/new.hbs
> Added navBarr, including styling, set up routes, fixed LOGIN/LOG OUT

- app.js
- controllers/posts.js
- models/post.js
- public/stylesheets/style.css
- routes/posts.js
- views/posts/index.hbs
> Add a like button

- controllers/users.js
- routes/users.js
`/users/photo/:id` will return the user's image with the appropriate [Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) header set, which can be embedded in `<img>` tags. If no image exists, [204 No Content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) is returned.
> Add a route for the user's profile photo as a raw image

- controllers/users.js
- public/stylesheets/style.css
- routes/users.js
- views/layout.hbs
- views/users/all.hbs
> Add an 'all profiles' page `/users/all`

- app.js
- controllers/posts.js
- models/post.js
- package-lock.json
- package.json
- routes/posts.js
- views/posts/index.hbs
- views/posts/new.hbs
> Added the ability to post images to the timeline.

- public/stylesheets/style.css
> Fix the all users page (a bracket got lost in merge conflict resolution)

- controllers/posts.js
- models/post.js
- public/stylesheets/style.css
- routes/posts.js
- views/posts/index.hbs
> Added post commenting

- public/stylesheets/style.css
- views/posts/index.hbs
> Timeline layout

- cypress.json
- cypress/integration/all_user_page_spec.js
- cypress/integration/user_can_sign_in_spec.js
- cypress/integration/user_can_submit_posts_spec.js
- cypress/plugins/index.js
- cypress/support/index.js
- package-lock.json
- package.json
> Added All Users page spec, updated other specs, corrected config.

- controllers/posts.js
> Set url hash after liking a post

- controllers/posts.js
- models/post.js
- public/stylesheets/style.css
- routes/posts.js
- views/posts/index.hbs
> Added images to comments, changed CSS

- public/stylesheets/style.css
- views/layout.hbs
- views/sessions/new.hbs
- views/users/new.hbs
> Added a bigger logo to signup/login page

- routes/posts.js
- views/posts/index.hbs
> Fix comments not appearing, only show comment image if one exists

- controllers/sessions.js
- views/sessions/new.hbs
> wrong login details error messages

- public/stylesheets/style.css
- views/users/edit_profile.hbs
User can see suggestions of what to put in their bio in the bio placeholder before the first time they fill in their bio. Prevented resizing of text box.
> User can see examples in bio placeholder

- app.js
- bin/www
- package-lock.json
- package.json
- util/mongoConnector.js
no more logging in every time the server restarts!
> Mongo-backed sessions

- controllers/posts.js
- routes/posts.js
- util/handlebarshelpers.js
- views/posts/index.hbs
> Comment delete button

- public/stylesheets/style.css
> profile picture is now perfect square

- controllers/users.js
- package-lock.json
- package.json
- routes/users.js
- views/users/profile.hbs
> Profile pages for other users

- public/stylesheets/style.css
- util/handlebarshelpers.js
- views/layout.hbs
- views/posts/index.hbs
- views/posts/new.hbs
- views/users/all.hbs
- views/users/profile.hbs
> Chonky styling
